:smtp_settings:
  :address: smtp.sendgrid.net
  :port: 25
  :authentication: :plain
  :user_name: ENV['SENDGRID_USERNAME']
  :password: ENV['SENDGRID_PASSWORD']
  :domain: ENV['SENDGRID_DOMAIN']    
:host: agiles-call4papers.heroku.com
:conference_name: Ágiles 2011
